# docker-compose.yaml
services:
  db:
    image: postgres:13
    container_name: pg-database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    ports:
      - "5433:5432"
    volumes:
      - ./docker_data/ny_taxi_postgres_data:/var/lib/postgresql/data:rw

  ingest_zones:
    image: taxi_ingest  # local image built from Dockerfile
    container_name: taxi_ingest_zones
    depends_on:
      - db
    command: > 
      --user root
      --password root
      --host db
      --port 5432
      --database ny_taxi
      --table zones
      --csv-url https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv
    restart: "no"

  ingest_trips:
    image: taxi_ingest  # local image built from Dockerfile
    container_name: taxi_ingest_trips
    depends_on:
      - db
      - ingest_zones
    command: > 
      --user root
      --password root
      --host db
      --port 5432
      --database ny_taxi
      --table green_trips
      --csv-url https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-10.csv.gz
    restart: "no"


  pg-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    user: '$UID:$GID'
    ports:
      - 8080:80
    depends_on:
      - db
      - ingest_trips
      - ingest_zones
    volumes:
      - ./docker_data/pgadmin_data:/var/lib/pgadmin

volumes:
  ny_taxi_postgres_data:
  pgadmin_data: